version: "3"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask-app-api
    ports:
    - "5000:5000"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server && celery -A tasks worker -l info
    # volumes: 
    #   - cache:/data
   
  # client:
  #   restart: always
  #   depends_on:
  #   - api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   image: react-flask-app-client
  #   ports:
  #     - "80:80"