FROM python:3.9
WORKDIR /app

COPY ./app/ ./app/requirements.txt ./app/api.py ./app/.flaskenv ./app/models.py ./app/controller.py ./app/test.db ./app/tasks.py ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
